# Generated by Django 4.2 on 2023-05-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_exp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=100)),
                ('total_expense', models.IntegerField(default=0)),
                ('total_limit', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=100)),
                ('total_expense', models.IntegerField(default=0)),
                ('total_limit', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='limit_val',
            fields=[
                ('limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('exp_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('food', 'food'), ('entertainment', 'entertainment'), ('stocks', 'stocks'), ('rent', 'rent'), ('emi', 'emi'), ('others', 'others')], default='others', max_length=100)),
                ('pay_mode', models.CharField(choices=[('cash', 'cash'), ('creditcard', 'creditcard'), ('debitcard', 'debitcard'), ('upi', 'upi'), ('onlinebanking', 'onlinebanking')], default='cash', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
