# Generated by Django 4.2 on 2023-05-03 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='daily_expense',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=1, size=31),
            preserve_default=False,
        ),
    ]
