# Generated by Django 4.2 on 2023-05-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_month_daily_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='daily_expense',
        ),
    ]
