# Generated by Django 4.2 on 2023-04-23 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_limit_alter_expense_user_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='limit',
            new_name='limit_val',
        ),
    ]
