# Generated by Django 4.2 on 2023-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_daily_id_daily_daily_id_daily_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='daily_exp',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=62),
        ),
    ]
